### ISSUE TITLE
unexpected keyword argument 'username' since upgraded ansible version

### ISSUE THREAD

**Issue by jviallon** [ansible-collections/kubernetes.core#541]
##### SUMMARY
Playbook doesn't work with ansible 2.13.5, with older version (2.9.27) playbook as described below is working fine and kubernetes resources are created properly

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
kubernetes.core.k8s

##### ANSIBLE VERSION
```
ansible [core 2.13.5]
  config file = None
  configured module search path = ['/home/runner/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.8/site-packages/ansible
  ansible collection location = /home/runner/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.8.13 (default, Jun 24 2022, 15:27:57) [GCC 8.5.0 20210514 (Red Hat 8.5.0-13)]
  jinja version = 3.1.2
  libyaml = True
```

##### COLLECTION VERSION
```
Collection      Version
--------------- -------
kubernetes.core 2.3.2 
```

##### CONFIGURATION
```
DEFAULT_BECOME_METHOD(/runner/ansible.cfg) = sudo
DEFAULT_BECOME_USER(/runner/ansible.cfg) = root
DEFAULT_TIMEOUT(/runner/ansible.cfg) = 60
```

##### STEPS TO REPRODUCE
playbook.yml
```yaml
---
- name: Deploy k8s-app
  hosts: localhost
  connection: local
  gather_facts: false
  roles:
    - {role: k8s-app}
```

k8s-app/tasks.yml
```yaml
---
- name: Deploy k8s-app on K8S cluster
  k8s:
    host: "{{ api_server }}"
    api_key: "{{ api_key }}"
    namespace: "{{ namespace }}"
    validate_certs: false
    definition: "{{ lookup('template', 'service.yml') }}"
```

##### EXPECTED RESULTS
service.yml is deployed on my kubernetes namespace same as it works today with ansible 2.9.27

##### ACTUAL RESULTS
```
Traceback (most recent call last):\n  File \"/home/ansible/.ansible/tmp/ansible-tmp-1668005821.104081-15-124334829768756/AnsiballZ_k8s.py\", line 107, in <module>\n    _ansiballz_main()\n  File \"/home/ansible/.ansible/tmp/ansible-tmp-1668005821.104081-15-124334829768756/AnsiballZ_k8s.py\", line 99, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/ansible/.ansible/tmp/ansible-tmp-1668005821.104081-15-124334829768756/AnsiballZ_k8s.py\", line 47, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.kubernetes.core.plugins.modules.k8s', init_globals=dict(_module_fqn='ansible_collections.kubernetes.core.plugins.modules.k8s', _modlib_path=modlib_path),\n  File \"/usr/lib64/python3.8/runpy.py\", line 207, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib64/python3.8/runpy.py\", line 97, in _run_module_code\n    _run_code(code, mod_globals, init_globals,\n  File \"/usr/lib64/python3.8/runpy.py\", line 87, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_kubernetes.core.k8s_payload_tic0ivf_/ansible_kubernetes.core.k8s_payload.zip/ansible_collections/kubernetes/core/plugins/modules/k8s.py\", line 486, in <module>\n  File \"/tmp/ansible_kubernetes.core.k8s_payload_tic0ivf_/ansible_kubernetes.core.k8s_payload.zip/ansible_collections/kubernetes/core/plugins/modules/k8s.py\", line 481, in main\n  File \"/tmp/ansible_kubernetes.core.k8s_payload_tic0ivf_/ansible_kubernetes.core.k8s_payload.zip/ansible_collections/kubernetes/core/plugins/module_utils/common.py\", line 253, in get_api_client\nTypeError: __call__() got an unexpected keyword argument 'username'\n",
```

**Comment by gravesm** [comment]
@jviallon What version of the python kubernetes client library are you using?

**Comment by jviallon** [comment]
Hello @gravesm , pythin kubernetes librery is 11.0.0
```shell
sh-4.4$ pip list  | grep kubernetes
kubernetes                     11.0.0
````

**Comment by jviallon** [comment]
I tested after upgrading kubernetes library to 25.3.0 and it works fine with my playbook. 

```shell 
sh-4.4$ pip list | grep kubernetes
kubernetes                     25.3.0
```

I close the issue.
